---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: calunga-release
subjects:
  - kind: ServiceAccount
    name: calunga-release
roleRef:
  kind: Role
  name: calunga-release
  apiGroup: rbac.authorization.k8s.io
