---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: calunga-release
rules:
  - apiGroups:
      - appstudio.redhat.com
    resources:
      - releases
      - releaseplans
      - snapshots
    verbs:
      - get
      - watch
      - list
