#!/bin/bash
set -euo pipefail

NEW_PKG="$1"
PKG_NAME="${NEW_PKG%%==*}"
VERSION="${NEW_PKG##*==}"
PKG_FILE="onboarded_packages/${PKG_NAME}.json"

# jq is in the github-action runner
jq --arg v "$VERSION" '.version = $v' "$PKG_FILE" > "${PKG_FILE}.tmp" && mv "${PKG_FILE}.tmp" "$PKG_FILE"
